# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Checkmarx AST Github Action
  # You may pin to the exact commit or the version.
  # uses: Checkmarx/ast-github-action@0fcee7e03446692b38464ac6ec3a47bf1deb1c27
        uses: Checkmarx/ast-github-action@2.0.9
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net
          # Provide the Tenant for AST portal URL
          cx_tenant: nfr_alexasecurity
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          # Select a Checkmarx Project Name
          project_name: jvl_githubaction
          # Branch name
          branch: ${{ github.head_ref || github.ref }}
          # Additional parameters for AST scan
          additional_params: --scan-types sast,kics,sca --threshold sast-high=130 --threshold sca-high=10
